---
- hosts: groupcommon
  become: yes
  tasks:
    - name: Task 1 install apache(httpd)
      yum:
        name: httpd
        state: latest
    - name: Task 2 start and enable apache
      service:
        name: httpd
        state: started
        enabled: yes
    - name: Task 3 create index.html
      file: 
        path: /var/www/html/index.html
        state: touch
    - name: Task 4 add a line to index.html
      lineinfile:
        path: /var/www/html/index.html
        line: "<h1>Hello World1!</h1>"
