---
- hosts: groupcommon
  become: yes
  tasks:
    - name: edit index.html file
      lineinfile: 
        path: /var/www/html/index.html
        line: "This is for when condtion with ansible hostname in the playbook "
      when: ansible_hostname == "3.88.141.86"
