- name: registered variable usage as a loop list
  hosts: all
  tasks:

    - name: retrieve the list of home directories
      command: ls /home
      register: home_dirs
    - debug: msg="Registered output is {{home_dirs}}"
