---
- hosts: groupcommon
  tasks:
    - name: deply the config file
      template: 
        src: /home/ansible/ketanlabansible/templates/template.j2
        dest: /home/ansible/ketanlabansible/templates/finalconfig.conf
  
