---
- name: install and restart apache
  hosts: groupcommon
  remote_user: ansible
  become: yes

  tasks: 
  - name: install epel repo
    yum: name=epel-release state=present
    async: 300
    poll: 1
  - name: install python bindings for SElinux
    yum: name={{item}} state=present
    with_items: 
    - libselinux-python
    - libsemanage-python

  - name: test to see if SELinux is running
    command: getenforce
    register: sestatus
    #changed_when: false
    changed_when: true

  - name: install apache
    yum: name=httpd state=present

  - name: start apache
    service: name=httpd state=started enabled=yes
